FROM node:alpine AS builder
WORKDIR /app
COPY frontend/. .
RUN npm install && \
    npm run build
FROM nginx:alpine
COPY --from=builder /app/dist/* /usr/share/nginx/html/
COPY docker/frontend/nginx.conf /etc/nginx/conf.d/default.conf