spring:
    flyway:
        baseline-on-migrate: true
        baselineVersion: 0
        table: schema_history
        locations: classpath:db/migration
        placeholderReplacement: false

    application:
        name: backend
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://test_db/test_db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
        username: test
        password: test
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
server:
    port: 8089